tunnel: ab031181-277c-435a-9f0e-2cd1853fe462
credentials-token: ./ab031181-277c-435a-9f0e-2cd1853fe462.json

ingress:
  - hostname: mhumble.io
    service: https://localhost:443
    originRequest:
      noTLSVerify: false
      http2Origin: true

  - service: http_status:404
